version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    networks:
      - frontend
  app:
    image: praqma/network-multitool
    networks:
      - frontend
      - backend
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    networks:
      - backend
networks:
  frontend:
  backend:
